export const platforms = ["Instagram", "YouTube"];

export const pageContentCategoryOptions = [
  // Technology & Digital
  { value: "Artificial Intelligence", label: "Artificial Intelligence" },
  { value: "Blockchain & Crypto", label: "Blockchain & Crypto" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "Programming", label: "Programming" },
  { value: "Web Development", label: "Web Development" },
  { value: "Mobile Apps", label: "Mobile Apps" },
  { value: "Gadget Reviews", label: "Gadget Reviews" },
  { value: "Tech News", label: "Tech News" },
  { value: "Software Tutorials", label: "Software Tutorials" },
  { value: "Cloud Computing", label: "Cloud Computing" },

  // Business & Finance
  { value: "Startups", label: "Startups" },
  { value: "Entrepreneurship", label: "Entrepreneurship" },
  { value: "Digital Marketing", label: "Digital Marketing" },
  { value: "Stock Market", label: "Stock Market" },
  { value: "Personal Finance", label: "Personal Finance" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "E-commerce", label: "E-commerce" },
  { value: "Leadership", label: "Leadership" },
  { value: "Productivity", label: "Productivity" },
  { value: "Remote Work", label: "Remote Work" },

  // Entertainment
  { value: "Movie Reviews", label: "Movie Reviews" },
  { value: "TV Show Recaps", label: "TV Show Recaps" },
  { value: "Celebrity News", label: "Celebrity News" },
  { value: "Music Releases", label: "Music Releases" },
  { value: "Anime & Manga", label: "Anime & Manga" },
  { value: "K-pop Culture", label: "K-pop Culture" },
  { value: "Broadway & Theater", label: "Broadway & Theater" },
  { value: "Comedy", label: "Comedy" },
  { value: "Fan Theories", label: "Fan Theories" },
  { value: "Reality TV", label: "Reality TV" },

  // Gaming
  { value: "Game Reviews", label: "Game Reviews" },
  { value: "Esports", label: "Esports" },
  { value: "Gaming News", label: "Gaming News" },
  { value: "Walkthroughs", label: "Walkthroughs" },
  { value: "Retro Gaming", label: "Retro Gaming" },
  { value: "VR Gaming", label: "VR Gaming" },
  { value: "Mobile Gaming", label: "Mobile Gaming" },
  { value: "Gaming Setup", label: "Gaming Setup" },
  { value: "Game Development", label: "Game Development" },
  { value: "Cosplay", label: "Cosplay" },

  // Science & Education
  { value: "Space Exploration", label: "Space Exploration" },
  { value: "Physics", label: "Physics" },
  { value: "Biology", label: "Biology" },
  { value: "Chemistry", label: "Chemistry" },
  { value: "Mathematics", label: "Mathematics" },
  { value: "Psychology", label: "Psychology" },
  { value: "Neuroscience", label: "Neuroscience" },
  { value: "Climate Science", label: "Climate Science" },
  { value: "Archaeology", label: "Archaeology" },
  { value: "Paleontology", label: "Paleontology" },

  // Travel
  { value: "Budget Travel", label: "Budget Travel" },
  { value: "Luxury Travel", label: "Luxury Travel" },
  { value: "Adventure Travel", label: "Adventure Travel" },
  { value: "Solo Travel", label: "Solo Travel" },
  { value: "Family Travel", label: "Family Travel" },
  { value: "Digital Nomads", label: "Digital Nomads" },
  { value: "Hotel Reviews", label: "Hotel Reviews" },
  { value: "Travel Hacks", label: "Travel Hacks" },
  { value: "Hidden Gems", label: "Hidden Gems" },
  { value: "Cultural Immersion", label: "Cultural Immersion" },

  // Fashion & Beauty
  { value: "Street Style", label: "Street Style" },
  { value: "Luxury Fashion", label: "Luxury Fashion" },
  { value: "Sustainable Fashion", label: "Sustainable Fashion" },
  { value: "Makeup Tutorials", label: "Makeup Tutorials" },
  { value: "Skincare Routine", label: "Skincare Routine" },
  { value: "Hair Care", label: "Hair Care" },
  { value: "Nail Art", label: "Nail Art" },
  { value: "Fashion History", label: "Fashion History" },
  { value: "Body Positivity", label: "Body Positivity" },
  { value: "Men's Grooming", label: "Men's Grooming" },

  // Food & Beverage
  { value: "Recipes", label: "Recipes" },
  { value: "Baking", label: "Baking" },
  { value: "Vegan Cooking", label: "Vegan Cooking" },
  { value: "Mixology", label: "Mixology" },
  { value: "Coffee Culture", label: "Coffee Culture" },
  { value: "Wine Tasting", label: "Wine Tasting" },
  { value: "Restaurant Reviews", label: "Restaurant Reviews" },
  { value: "Food Science", label: "Food Science" },
  { value: "International Cuisine", label: "International Cuisine" },
  { value: "Meal Prep", label: "Meal Prep" },

  // Health & Fitness
  { value: "Weight Loss", label: "Weight Loss" },
  { value: "Muscle Building", label: "Muscle Building" },
  { value: "Yoga", label: "Yoga" },
  { value: "Meditation", label: "Meditation" },
  { value: "Mental Health", label: "Mental Health" },
  { value: "Nutrition", label: "Nutrition" },
  { value: "Running", label: "Running" },
  { value: "Cycling", label: "Cycling" },
  { value: "Home Workouts", label: "Home Workouts" },
  { value: "Sports Medicine", label: "Sports Medicine" },

  // Lifestyle
  { value: "Minimalism", label: "Minimalism" },
  { value: "Parenting", label: "Parenting" },
  { value: "Relationships", label: "Relationships" },
  { value: "Self-Improvement", label: "Self-Improvement" },
  { value: "DIY Projects", label: "DIY Projects" },
  { value: "Home Organization", label: "Home Organization" },
  { value: "Gardening", label: "Gardening" },
  { value: "Pet Care", label: "Pet Care" },
  { value: "Sustainable Living", label: "Sustainable Living" },
  { value: "Feng Shui", label: "Feng Shui" },

  // Arts & Creativity
  { value: "Digital Art", label: "Digital Art" },
  { value: "Photography", label: "Photography" },
  { value: "Creative Writing", label: "Creative Writing" },
  { value: "Graphic Design", label: "Graphic Design" },
  { value: "Crafting", label: "Crafting" },
  { value: "Pottery", label: "Pottery" },
  { value: "Street Art", label: "Street Art" },
  { value: "Art History", label: "Art History" },
  { value: "Calligraphy", label: "Calligraphy" },
  { value: "Interior Design", label: "Interior Design" },

  // Sports
  { value: "Football", label: "Football" },
  { value: "Basketball", label: "Basketball" },
  { value: "Tennis", label: "Tennis" },
  { value: "Golf", label: "Golf" },
  { value: "Olympics", label: "Olympics" },
  { value: "Extreme Sports", label: "Extreme Sports" },
  { value: "Water Sports", label: "Water Sports" },
  { value: "Winter Sports", label: "Winter Sports" },
  { value: "Martial Arts", label: "Martial Arts" },
  { value: "Athlete Profiles", label: "Athlete Profiles" },

  // Automotive
  { value: "Car Reviews", label: "Car Reviews" },
  { value: "Electric Vehicles", label: "Electric Vehicles" },
  { value: "Classic Cars", label: "Classic Cars" },
  { value: "Car Maintenance", label: "Car Maintenance" },
  { value: "Racing", label: "Racing" },
  { value: "Motorcycles", label: "Motorcycles" },
  { value: "Bicycles", label: "Bicycles" },
  { value: "Auto Tech", label: "Auto Tech" },
  { value: "Off-Roading", label: "Off-Roading" },
  { value: "Car Culture", label: "Car Culture" },

  // Politics & Society
  { value: "Current Events", label: "Current Events" },
  { value: "Social Justice", label: "Social Justice" },
  { value: "Environmental Policy", label: "Environmental Policy" },
  { value: "Human Rights", label: "Human Rights" },
  { value: "Philosophy", label: "Philosophy" },
  { value: "History", label: "History" },
  { value: "Economics", label: "Economics" },
  { value: "Urban Planning", label: "Urban Planning" },
  { value: "Futurism", label: "Futurism" },
  { value: "Cultural Studies", label: "Cultural Studies" },

  // Special Interest
  { value: "True Crime", label: "True Crime" },
  { value: "Paranormal", label: "Paranormal" },
  { value: "Conspiracy Theories", label: "Conspiracy Theories" },
  { value: "Astrology", label: "Astrology" },
  { value: "Tarot", label: "Tarot" },
  { value: "Collectibles", label: "Collectibles" },
  { value: "Genealogy", label: "Genealogy" },
  { value: "Alternative Medicine", label: "Alternative Medicine" },
  { value: "Survivalism", label: "Survivalism" },
  { value: "Hobby Farming", label: "Hobby Farming" }
];

export const audienceTypeOptions = [
  // Age-Based
  { value: "Children", label: "Children (0-12)" },
  { value: "Teens", label: "Teens (13-19)" },
  { value: "Young Adults", label: "Young Adults (20-30)" },
  { value: "Millennials", label: "Millennials (25-40)" },
  { value: "Adults", label: "Adults (30-50)" },
  { value: "Middle Aged", label: "Middle Aged (40-60)" },
  { value: "Seniors", label: "Seniors (50+)" },
  { value: "Elderly", label: "Elderly (65+)" },

  // Professions
  { value: "Students", label: "Students" },
  { value: "College Students", label: "College Students" },
  { value: "Professionals", label: "Professionals" },
  { value: "Entrepreneurs", label: "Entrepreneurs" },
  { value: "Freelancers", label: "Freelancers" },
  { value: "Remote Workers", label: "Remote Workers" },
  { value: "Healthcare Workers", label: "Healthcare Workers" },
  { value: "Teachers", label: "Teachers" },
  { value: "Engineers", label: "Engineers" },
  { value: "IT Professionals", label: "IT Professionals" },
  { value: "Artists", label: "Artists" },
  { value: "Creatives", label: "Creatives (Designers, Writers)" },
  { value: "Blue Collar Workers", label: "Blue Collar Workers" },
  { value: "Executives", label: "Executives" },
  { value: "Retirees", label: "Retirees" },

  // Family & Lifestyle
  { value: "Parents", label: "Parents" },
  { value: "New Parents", label: "New Parents (0-3 years)" },
  { value: "Single Parents", label: "Single Parents" },
  { value: "Homeowners", label: "Homeowners" },
  { value: "Renters", label: "Renters" },
  { value: "Pet Owners", label: "Pet Owners" },
  { value: "Dog Owners", label: "Dog Owners" },
  { value: "Cat Owners", label: "Cat Owners" },
  { value: "Fitness Enthusiasts", label: "Fitness Enthusiasts" },
  { value: "Gamers", label: "Gamers" },
  { value: "Travelers", label: "Travelers" },
  { value: "Frequent Flyers", label: "Frequent Flyers" },
  { value: "Foodies", label: "Foodies" },
  { value: "Vegetarians", label: "Vegetarians" },
  { value: "Vegans", label: "Vegans" },

  // Interests & Hobbies
  { value: "Tech Enthusiasts", label: "Tech Enthusiasts" },
  { value: "Photographers", label: "Photographers" },
  { value: "Musicians", label: "Musicians" },
  { value: "Book Lovers", label: "Book Lovers" },
  { value: "Movie Buffs", label: "Movie Buffs" },
  { value: "Anime Fans", label: "Anime Fans" },
  { value: "Sports Fans", label: "Sports Fans" },
  { value: "Outdoor Adventurers", label: "Outdoor Adventurers" },
  { value: "Gardening Enthusiasts", label: "Gardening Enthusiasts" },
  { value: "DIYers", label: "DIYers" },
  { value: "Luxury Shoppers", label: "Luxury Shoppers" },
  { value: "Thrift Shoppers", label: "Thrift Shoppers" },
  { value: "Investors", label: "Investors" },
  { value: "Minimalists", label: "Minimalists" },
  { value: "Environmentalists", label: "Environmentalists" }
];

export const adCategoryOptions = [
  // Technology & Digital  
  { value: "Smartphones", label: "Smartphones" },
  { value: "Laptops", label: "Laptops" },
  { value: "Smartwatches", label: "Smartwatches" },
  { value: "Headphones", label: "Headphones" },
  { value: "Drones", label: "Drones" },
  { value: "VR Headsets", label: "VR Headsets" },
  { value: "Gaming Consoles", label: "Gaming Consoles" },
  { value: "Cameras", label: "Cameras" },
  { value: "Printers", label: "Printers" },
  { value: "Software Tools", label: "Software Tools" },

  // Fashion & Apparel  
  { value: "Men's Shoes", label: "Men's Shoes" },
  { value: "Women's Shoes", label: "Women's Shoes" },
  { value: "Sneakers", label: "Sneakers" },
  { value: "High Heels", label: "High Heels" },
  { value: "Sandals", label: "Sandals" },
  { value: "Handbags", label: "Handbags" },
  { value: "Watches", label: "Watches" },
  { value: "Sunglasses", label: "Sunglasses" },
  { value: "Jewelry", label: "Jewelry" },
  { value: "Men's Clothing", label: "Men's Clothing" },
  { value: "Women's Clothing", label: "Women's Clothing" },
  { value: "Kids' Fashion", label: "Kids' Fashion" },
  { value: "Winter Wear", label: "Winter Wear" },
  { value: "Sportswear", label: "Sportswear" },
  { value: "Luxury Fashion", label: "Luxury Fashion" },

  // Beauty & Cosmetics  
  { value: "Skincare", label: "Skincare" },
  { value: "Makeup", label: "Makeup" },
  { value: "Haircare", label: "Haircare" },
  { value: "Perfumes", label: "Perfumes" },
  { value: "Nail Products", label: "Nail Products" },
  { value: "Beauty Tools", label: "Beauty Tools" },
  { value: "Men's Grooming", label: "Men's Grooming" },
  { value: "Organic Beauty", label: "Organic Beauty" },
  { value: "Tattoo Supplies", label: "Tattoo Supplies" },
  { value: "Cosmetic Surgery", label: "Cosmetic Surgery" },

  // Entertainment & Media  
  { value: "Movies", label: "Movies" },
  { value: "TV Shows", label: "TV Shows" },
  { value: "Anime", label: "Anime" },
  { value: "K-Dramas", label: "K-Dramas" },
  { value: "Music Albums", label: "Music Albums" },
  { value: "Concerts", label: "Concerts" },
  { value: "Streaming Services", label: "Streaming Services" },
  { value: "Video Games", label: "Video Games" },
  { value: "Board Games", label: "Board Games" },
  { value: "Comic Books", label: "Comic Books" },

  // Home & Living  
  { value: "Furniture", label: "Furniture" },
  { value: "Home Decor", label: "Home Decor" },
  { value: "Kitchenware", label: "Kitchenware" },
  { value: "Bedding", label: "Bedding" },
  { value: "Lighting", label: "Lighting" },
  { value: "Gardening", label: "Gardening" },
  { value: "Smart Home", label: "Smart Home" },
  { value: "Home Appliances", label: "Home Appliances" },
  { value: "Cleaning Supplies", label: "Cleaning Supplies" },
  { value: "Pet Supplies", label: "Pet Supplies" },

  // Health & Wellness  
  { value: "Vitamins", label: "Vitamins" },
  { value: "Protein Supplements", label: "Protein Supplements" },
  { value: "Weight Loss", label: "Weight Loss" },
  { value: "Yoga Mats", label: "Yoga Mats" },
  { value: "Fitness Equipment", label: "Fitness Equipment" },
  { value: "Mental Wellness", label: "Mental Wellness" },
  { value: "Medical Devices", label: "Medical Devices" },
  { value: "Elderly Care", label: "Elderly Care" },
  { value: "Sexual Wellness", label: "Sexual Wellness" },
  { value: "Essential Oils", label: "Essential Oils" },

  // Automotive  
  { value: "Cars", label: "Cars" },
  { value: "Motorcycles", label: "Motorcycles" },
  { value: "Bicycles", label: "Bicycles" },
  { value: "Tires", label: "Tires" },
  { value: "Car Audio", label: "Car Audio" },
  { value: "Car Accessories", label: "Car Accessories" },
  { value: "EV Chargers", label: "EV Chargers" },
  { value: "Auto Parts", label: "Auto Parts" },
  { value: "Car Wash", label: "Car Wash" },
  { value: "Vehicle Rentals", label: "Vehicle Rentals" },

  // Food & Beverage  
  { value: "Gourmet Food", label: "Gourmet Food" },
  { value: "Organic Food", label: "Organic Food" },
  { value: "Coffee & Tea", label: "Coffee & Tea" },
  { value: "Wine & Spirits", label: "Wine & Spirits" },
  { value: "Vegan Products", label: "Vegan Products" },
  { value: "Kitchen Gadgets", label: "Kitchen Gadgets" },
  { value: "Restaurant Deals", label: "Restaurant Deals" },
  { value: "Meal Kits", label: "Meal Kits" },
  { value: "Snacks", label: "Snacks" },
  { value: "Food Delivery", label: "Food Delivery" },

  // Travel & Leisure  
  { value: "Hotels", label: "Hotels" },
  { value: "Flight Tickets", label: "Flight Tickets" },
  { value: "Vacation Packages", label: "Vacation Packages" },
  { value: "Cruises", label: "Cruises" },
  { value: "Backpacks", label: "Backpacks" },
  { value: "Luggage", label: "Luggage" },
  { value: "Travel Insurance", label: "Travel Insurance" },
  { value: "Adventure Tours", label: "Adventure Tours" },
  { value: "Camping Gear", label: "Camping Gear" },
  { value: "Ski Resorts", label: "Ski Resorts" },

  // Business & Services  
  { value: "Freelance Services", label: "Freelance Services" },
  { value: "Web Hosting", label: "Web Hosting" },
  { value: "Domain Names", label: "Domain Names" },
  { value: "Office Supplies", label: "Office Supplies" },
  { value: "Printing Services", label: "Printing Services" },
  { value: "Virtual Assistants", label: "Virtual Assistants" },
  { value: "Business Coaching", label: "Business Coaching" },
  { value: "POS Systems", label: "POS Systems" },
  { value: "CRM Software", label: "CRM Software" },
  { value: "Accounting Tools", label: "Accounting Tools" },

  // Kids & Babies  
  { value: "Baby Clothing", label: "Baby Clothing" },
  { value: "Diapers", label: "Diapers" },
  { value: "Strollers", label: "Strollers" },
  { value: "Toys", label: "Toys" },
  { value: "Baby Food", label: "Baby Food" },
  { value: "Kids' Bikes", label: "Kids' Bikes" },
  { value: "Educational Toys", label: "Educational Toys" },
  { value: "Nursery Decor", label: "Nursery Decor" },
  { value: "Baby Monitors", label: "Baby Monitors" },
  { value: "Children's Books", label: "Children's Books" },

  // Hobbies & Collectibles  
  { value: "Trading Cards", label: "Trading Cards" },
  { value: "Action Figures", label: "Action Figures" },
  { value: "Model Kits", label: "Model Kits" },
  { value: "Vinyl Records", label: "Vinyl Records" },
  { value: "Art Supplies", label: "Art Supplies" },
  { value: "Musical Instruments", label: "Musical Instruments" },
  { value: "Drones (Hobby)", label: "Drones (Hobby)" },
  { value: "RC Cars", label: "RC Cars" },
  { value: "Coin Collecting", label: "Coin Collecting" },
  { value: "Stamp Collecting", label: "Stamp Collecting" },

  // Special Interest  
  { value: "Astrology", label: "Astrology" },
  { value: "Tarot Cards", label: "Tarot Cards" },
  { value: "Crystals", label: "Crystals" },
  { value: "Horror Merch", label: "Horror Merch" },
  { value: "Anime Merch", label: "Anime Merch" },
  { value: "K-Pop Merch", label: "K-Pop Merch" },
  { value: "Fantasy Books", label: "Fantasy Books" },
  { value: "Sci-Fi Collectibles", label: "Sci-Fi Collectibles" },
  { value: "Meditation Tools", label: "Meditation Tools" },
  { value: "Spiritual Retreats", label: "Spiritual Retreats" },
];